server:
  port: 8000
  servlet:
    context-path: /api

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:users
      driver-class-name: org.h2.Driver

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh", "metrics"]